In [1]:
import pandas as pd
import numpy as np

In [91]:
xlsx = pd.ExcelFile("mobile_customers.xlsx")

for sheet in xlsx.sheet_names:
    df = pd.read_excel(xlsx, sheet)
    df.to_csv(f"{sheet}.csv", index=False)

In [34]:
df

,Unnamed: 0,customer_id,date_registered,username,name,gender,address,email,birthdate,current_location,residence,employer,job,age,salary,credit_card_provider,credit_card_number,credit_card_security_code,credit_card_expire
0,0,24c9d2d0-d0d3-4a90-9a3a-e00e4aac99bd,2021-09-29,robertsbryan,Jonathan Snyder,M,"24675 Susan Valley\nNorth Dianabury, MO 02475",marcus58@hotmail.com,1978-03-11,"['78.937112', '71.260464']","195 Brandi Junctions\nNew Julieberg, NE 63410","Byrd, Welch and Holt",Chief Technology Officer,49,53979,VISA 19 digit,38985874269846,994,2023-10-27 00:00:00
1,1,7b2bc220-0296-4914-ba46-d6cc6a55a62a,2019-08-17,egarcia,Susan Dominguez,F,"4212 Cheryl Inlet\nPort Davidmouth, NC 54884",alexanderkathy@hotmail.com,1970-11-29,"['-24.1692185', '100.746122']","58272 Brown Isle Apt. 698\nPort Michael, HI 04693",Hurst PLC,Data scientist,43,81510,Discover,6525743622515979,163,2023-07-30 00:00:00
2,2,06febdf9-07fb-4a1b-87d7-a5f97d9a5faf,2019-11-01,turnermegan,Corey Hebert,M,"07388 Coleman Prairie\nLake Amy, IA 78695",vwood@gmail.com,2009-04-23,"['8.019908', '-19.603269']","36848 Jones Lane Suite 282\nMarquezbury, ID 26822","Mora, Caldwell and Guerrero",Chief Operating Officer,47,205345,VISA 16 digit,4010729915028682247,634,2023-04-26 00:00:00
3,3,23df88e5-5dd3-46af-ac0d-0c6bd92e4b96,2021-12-31,richardcampbell,Latasha Griffin,F,"PSC 6217, Box 2610\nAPO AA 53585",kathleen36@gmail.com,1992-07-27,"['62.497506', '2.717198']","317 Lamb Cape Apt. 884\nLake Amy, DC 79074",Patel PLC,Counselling psychologist,34,116095,VISA 16 digit,4854862659569207844,7957,2023-10-31 00:00:00
4,4,6069c2d7-7905-4993-a155-64f6aba143b1,2020-08-09,timothyjackson,Colleen Wheeler,F,"0325 Potter Roads\nLake Lisashire, NM 77502",johnbest@hotmail.com,1989-09-16,"['73.7924695', '-80.314720']","21936 Mary Islands\nMendozafort, TN 37124",Smith-Mejia,Mining engineer,57,107529,JCB 16 digit,213152724828217,72,2023-05-28 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,d6424be2-4351-4535-8bca-34775cdcc411,2021-09-12,weaverpatrick,Courtney Li,F,Unit 5088 Box 8191\nDPO AA 18373,jlawson@yahoo.com,1975-07-13,"['-19.0218865', '20.492347']","53290 Jessica Pike Suite 808\nNorth Patricia, ...",Palmer Inc,Press photographer,57,241058,Diners Club / Carte Blanche,4522452929113284,448,2023-06-27 00:00:00
9996,9996,d9ac8491-5e97-46ba-a7f3-d12491e9487c,2020-08-15,bmartinez,Terri Hawkins,F,"38388 Joseph Drive Apt. 442\nPort Thomas, NH 1...",rebeccaramirez@gmail.com,1940-10-19,"['-24.0879205', '-39.253362']","21271 Anthony Ports Apt. 438\nButlerport, ND 7...","Adams, Mckee and Maldonado",Phytotherapist,33,26398,VISA 13 digit,4647267952761431,227,2023-12-31 00:00:00
9997,9997,1d5e94c5-bfc9-439d-84f6-6bf6c613cb16,2019-10-24,jphelps,Crystal Patterson,F,"4880 Newman Square\nColeberg, AK 41248",brownsandra@gmail.com,1994-12-27,"['-42.7290705', '-48.446354']","7949 Simmons Cape\nNew Glendaborough, NJ 90980",Fernandez Group,Chartered accountant,24,244563,Discover,2286190388812018,877,2023-06-24 00:00:00
9998,9998,15549c9b-caa9-413f-9dd5-84b43648ca23,2020-08-14,josephdavis,Jeff Edwards,M,"68770 Wright Plaza\nStevemouth, NM 11812",wreed@gmail.com,1961-03-07,"['-8.8195715', '17.887337']","3421 Katherine Wall\nEast Markside, NE 95730","Warner, Munoz and Franklin",Oceanographer,44,232825,American Express,3582143232994788,92,2023-04-28 00:00:00
9999,9999,2993d9a9-c67f-4383-ae28-c55537b76f06,2020-04-04,barnesandrew,David Nelson,M,"PSC 6109, Box 8247\nAPO AA 57422",nfields@yahoo.com,2015-10-27,"['-40.207589', '76.263738']",Unit 7808 Box 8797\nDPO AA 44228,Payne Ltd,Town planner,48,168859,Mastercard,180039538272220,445,2023-12-30 00:00:00

## 1:- Dropping the Important Columns

In [92]:
cols_to_drop = ['username', 'name','gender','address','email','current_location','residence','employer','credit_card_number','credit_card_security_code','job']
to_mask_data=df.drop(columns=cols_to_drop) # storing the unanonimised data in to_mask_data for masking
to_mask_data

,Unnamed: 0,customer_id,date_registered,birthdate,age,salary,credit_card_provider,credit_card_expire
0,0,24c9d2d0-d0d3-4a90-9a3a-e00e4aac99bd,2021-09-29,1978-03-11,49,53979,VISA 19 digit,2023-10-27 00:00:00
1,1,7b2bc220-0296-4914-ba46-d6cc6a55a62a,2019-08-17,1970-11-29,43,81510,Discover,2023-07-30 00:00:00
2,2,06febdf9-07fb-4a1b-87d7-a5f97d9a5faf,2019-11-01,2009-04-23,47,205345,VISA 16 digit,2023-04-26 00:00:00
3,3,23df88e5-5dd3-46af-ac0d-0c6bd92e4b96,2021-12-31,1992-07-27,34,116095,VISA 16 digit,2023-10-31 00:00:00
4,4,6069c2d7-7905-4993-a155-64f6aba143b1,2020-08-09,1989-09-16,57,107529,JCB 16 digit,2023-05-28 00:00:00
...,...,...,...,...,...,...,...,...
9995,9995,d6424be2-4351-4535-8bca-34775cdcc411,2021-09-12,1975-07-13,57,241058,Diners Club / Carte Blanche,2023-06-27 00:00:00
9996,9996,d9ac8491-5e97-46ba-a7f3-d12491e9487c,2020-08-15,1940-10-19,33,26398,VISA 13 digit,2023-12-31 00:00:00
9997,9997,1d5e94c5-bfc9-439d-84f6-6bf6c613cb16,2019-10-24,1994-12-27,24,244563,Discover,2023-06-24 00:00:00
9998,9998,15549c9b-caa9-413f-9dd5-84b43648ca23,2020-08-14,1961-03-07,44,232825,American Express,2023-04-28 00:00:00
9999,9999,2993d9a9-c67f-4383-ae28-c55537b76f06,2020-04-04,2015-10-27,48,168859,Mastercard,2023-12-30 00:00:00

## 2:- Maksing the leftover Columns

## 2.1:- Masking the Dates

In [93]:
to_mask_data['date_registered']=pd.to_datetime(to_mask_data['date_registered'])
to_mask_data['date_registered']=to_mask_data['date_registered'].dt.year  # to mask the date_registration 
to_mask_data

,Unnamed: 0,customer_id,date_registered,birthdate,age,salary,credit_card_provider,credit_card_expire
0,0,24c9d2d0-d0d3-4a90-9a3a-e00e4aac99bd,2021,1978-03-11,49,53979,VISA 19 digit,2023-10-27 00:00:00
1,1,7b2bc220-0296-4914-ba46-d6cc6a55a62a,2019,1970-11-29,43,81510,Discover,2023-07-30 00:00:00
2,2,06febdf9-07fb-4a1b-87d7-a5f97d9a5faf,2019,2009-04-23,47,205345,VISA 16 digit,2023-04-26 00:00:00
3,3,23df88e5-5dd3-46af-ac0d-0c6bd92e4b96,2021,1992-07-27,34,116095,VISA 16 digit,2023-10-31 00:00:00
4,4,6069c2d7-7905-4993-a155-64f6aba143b1,2020,1989-09-16,57,107529,JCB 16 digit,2023-05-28 00:00:00
...,...,...,...,...,...,...,...,...
9995,9995,d6424be2-4351-4535-8bca-34775cdcc411,2021,1975-07-13,57,241058,Diners Club / Carte Blanche,2023-06-27 00:00:00
9996,9996,d9ac8491-5e97-46ba-a7f3-d12491e9487c,2020,1940-10-19,33,26398,VISA 13 digit,2023-12-31 00:00:00
9997,9997,1d5e94c5-bfc9-439d-84f6-6bf6c613cb16,2019,1994-12-27,24,244563,Discover,2023-06-24 00:00:00
9998,9998,15549c9b-caa9-413f-9dd5-84b43648ca23,2020,1961-03-07,44,232825,American Express,2023-04-28 00:00:00
9999,9999,2993d9a9-c67f-4383-ae28-c55537b76f06,2020,2015-10-27,48,168859,Mastercard,2023-12-30 00:00:00

In [94]:
to_mask_data['birthdate']=pd.to_datetime(to_mask_data['birthdate'])
to_mask_data['birthdate']=to_mask_data['birthdate'].dt.year  # to mask the date_registration 
to_mask_data

,Unnamed: 0,customer_id,date_registered,birthdate,age,salary,credit_card_provider,credit_card_expire
0,0,24c9d2d0-d0d3-4a90-9a3a-e00e4aac99bd,2021,1978,49,53979,VISA 19 digit,2023-10-27 00:00:00
1,1,7b2bc220-0296-4914-ba46-d6cc6a55a62a,2019,1970,43,81510,Discover,2023-07-30 00:00:00
2,2,06febdf9-07fb-4a1b-87d7-a5f97d9a5faf,2019,2009,47,205345,VISA 16 digit,2023-04-26 00:00:00
3,3,23df88e5-5dd3-46af-ac0d-0c6bd92e4b96,2021,1992,34,116095,VISA 16 digit,2023-10-31 00:00:00
4,4,6069c2d7-7905-4993-a155-64f6aba143b1,2020,1989,57,107529,JCB 16 digit,2023-05-28 00:00:00
...,...,...,...,...,...,...,...,...
9995,9995,d6424be2-4351-4535-8bca-34775cdcc411,2021,1975,57,241058,Diners Club / Carte Blanche,2023-06-27 00:00:00
9996,9996,d9ac8491-5e97-46ba-a7f3-d12491e9487c,2020,1940,33,26398,VISA 13 digit,2023-12-31 00:00:00
9997,9997,1d5e94c5-bfc9-439d-84f6-6bf6c613cb16,2019,1994,24,244563,Discover,2023-06-24 00:00:00
9998,9998,15549c9b-caa9-413f-9dd5-84b43648ca23,2020,1961,44,232825,American Express,2023-04-28 00:00:00
9999,9999,2993d9a9-c67f-4383-ae28-c55537b76f06,2020,2015,48,168859,Mastercard,2023-12-30 00:00:00

In [95]:
to_mask_data['credit_card_expire'] = pd.to_datetime(to_mask_data['credit_card_expire'],errors='coerce')
to_mask_data['credit_card_expire'] = (to_mask_data['credit_card_expire'].dt.year)
to_mask_data

,Unnamed: 0,customer_id,date_registered,birthdate,age,salary,credit_card_provider,credit_card_expire
0,0,24c9d2d0-d0d3-4a90-9a3a-e00e4aac99bd,2021,1978,49,53979,VISA 19 digit,2023.0
1,1,7b2bc220-0296-4914-ba46-d6cc6a55a62a,2019,1970,43,81510,Discover,2023.0
2,2,06febdf9-07fb-4a1b-87d7-a5f97d9a5faf,2019,2009,47,205345,VISA 16 digit,2023.0
3,3,23df88e5-5dd3-46af-ac0d-0c6bd92e4b96,2021,1992,34,116095,VISA 16 digit,2023.0
4,4,6069c2d7-7905-4993-a155-64f6aba143b1,2020,1989,57,107529,JCB 16 digit,2023.0
...,...,...,...,...,...,...,...,...
9995,9995,d6424be2-4351-4535-8bca-34775cdcc411,2021,1975,57,241058,Diners Club / Carte Blanche,2023.0
9996,9996,d9ac8491-5e97-46ba-a7f3-d12491e9487c,2020,1940,33,26398,VISA 13 digit,2023.0
9997,9997,1d5e94c5-bfc9-439d-84f6-6bf6c613cb16,2019,1994,24,244563,Discover,2023.0
9998,9998,15549c9b-caa9-413f-9dd5-84b43648ca23,2020,1961,44,232825,American Express,2023.0
9999,9999,2993d9a9-c67f-4383-ae28-c55537b76f06,2020,2015,48,168859,Mastercard,2023.0

In [96]:
to_mask_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            10000 non-null  int64
 1   customer_id           10000 non-null  object
 2   date_registered       10000 non-null  int32
 3   birthdate             10000 non-null  int32
 4   age                   10000 non-null  int64
 5   salary                10000 non-null  int64
 6   credit_card_provider  10000 non-null  object
 7   credit_card_expire    9465 non-null   float64
dtypes: float64(1), int32(2), int64(3), object(2)
memory usage: 547.0+ KB